"""add_quality_fields_and_cleaned_path

Revision ID: 7eaa63be1fcf
Revises: cc1e1fea29c3
Create Date: 2026-09-13 21:51:50.535832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eaa63be1fcf'
down_revision: Union[str, Sequence[str], None] = 'cc1e1fea29c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('cleaned_path', sa.String(), nullable=True))
    op.add_column('research_questions', sa.Column('quality_score', sa.Integer(), nullable=False))
    op.add_column('research_questions', sa.Column('quality_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_questions', 'quality_label')
    op.drop_column('research_questions', 'quality_score')
    op.drop_column('datasets', 'cleaned_path')
    # ### end Alembic commands ###
